const demoData = [
  {
    "title":' Barbecue Platter',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/barbecue_platter.jpeg',
    "catagories":'lunch',
    "price":900,
    "keys":"100123"
  },
  {
    "title":'Fried Chicken ',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Fried_Chicken.png',
    "catagories":'lunch',
    "price":500,
    "keys":"1001234",
  },
  {
    "title":'Rajma Chawal',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Rajma_Chawal.jpeg',
    "catagories":'lunch',
    "price":400,
    "keys":"100145234",
  },
  {
    "title":'Masala Dosa',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Masala_Dosa.jpeg',
    "catagories":'lunch',
    "price":350,
    "keys":"10012347",
  },
  {
    "title":'White Sauce Pasta',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/white_sauce_pasta.jpeg',
    "catagories":'lunch',
    "price":500,
    "keys":"1001423",
  },
  {
    "title":'Dal Makhani',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Dal_Makhani.jpeg',
    "catagories":'lunch',
    "price":250,
    "keys":"1770123",
  },
  {
    "title":'Chicken Biryani',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/chicken_biryani.jpeg',
    "catagories":'dinner',
    "price":500,
    "keys":"108453",
  },
  {
    "title":'Lemon Salmon',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Lemon_Salmon.jpeg',
    "catagories":'dinner',
    "price":700,
    "keys":"199123",
  },
  {
    "title":'Kadhai Paneer',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Kadai_Paneer.jpeg',
    "catagories":'dinner',
    "price":350,
    "keys":"10483",
  },
  {
    "title":'Dum Aloo',
    "subtitle":'How we dream about our future',
    "description": 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/dum_aloo.jpeg',
    "catagories":'dinner',
    "price":300,
    "keys":"107484",
  },
  {
    "title":'Chilli Chicken Gravy',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/chilli_chicken.jpeg',
    "catagories":'dinner',
    "price":400,
    "keys":"114414",
  },
  {
    "title":'Cheesy French Fries',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Cheesy_French_Fries.jpeg',
    "catagories":'dinner',
    "price":250,
    "keys":"1178123",
  },
  {
    "title":'Waffles',
    "subtitle":'How we dream about our future',
    "description":'A waffle is a dish made from leavened batter or dough that is cooked between two plates that are patterned to give a characteristic size, shape, and surface impression. There are many variations based on the type of waffle iron and recipe used.     ',
    "img":'./Images/Waffles.jpeg',
    "catagories":'breakfast',
    "price":350,
    "keys":"1001234854",
  },
  {
    "title":'',
    "subtitle":'Egg Omelette',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Egg_Omelette.jpeg',
    "catagories":'breakfast',
    "price":250,
    "keys":"10012374874",
  },
  {
    "title":'Poha',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Poha.jpeg',
    "catagories":'breakfast',
    "price":150,
    "keys":"10014564723",
  },
  {
    "title":'Sandwiches',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Sandwiches.png',
    "catagories":'breakfast',
    "price":100,
    "keys":"1001778623",
  },
  {
    "title":'Aloo Parantha',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Aloo_Parantha.webp',
    "catagories":'breakfast',
    "price":200,
    "keys":"100123545444",
  },
  {
    "title":'Oatmeal',
    "subtitle":'How we dream about our future',
    "description":'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ab a hic soluta in accusantium aliquam tenetur inventore velit repellendus placeat, vel laudantium quos vitae recusandae nihil assumenda veritatis nisi.',
    "img":'Images/Oatmeal.jpeg',
    "catagories":'breakfast',
    "price":150,
    "keys":"100142447423",
  },
]
export default demoData;
